name: CI

on:
    pull_request:
        branches:
            - "*"

jobs:
    frontend-lint:
        name: Check lint FE
        runs-on: ubuntu-latest
        container: node:lts
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: install packages
              run: npm i
              working-directory: ./frontend-major
            - name: run lint
              run: npm run lint
              working-directory: ./frontend-major
    backend-lint:
        name: Check lint BE
        runs-on: ubuntu-latest
        container: node:lts
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: install packages
              run: npm i
              working-directory: ./backend-major
            - name: run lint
              run: npm run lint
              working-directory: ./backend-major

    frontend-check-build:
        name: Check Build FE
        needs: frontend-lint
        runs-on: ubuntu-latest
        timeout-minutes: 5
        container: node:lts
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: install packages
              run: npm ci
              working-directory: ./frontend-major
            - name: run build
              run: npm run build
              working-directory: ./frontend-major
              
    backend-check-build:
        name: Check Build BE
        needs: backend-lint
        runs-on: ubuntu-latest
        timeout-minutes: 5
        container: node:lts
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: install packages
              run: npm ci
              working-directory: ./backend-major
            - name: run build
              run: npm run build
              working-directory: ./backend-major
